python3 test.py --model-path /scratch/nlp/jiazixia/rl_enhanced/PartialLabelingCSL-zsc/outputs/neg/rps7_time1/model-12-1283.ckpt
python3 test.py --model-path /scratch/nlp/jiazixia/rl_enhanced/PartialLabelingCSL-zsc/outputs/neg/rps7_time1/model-13-1283.ckpt
python3 test.py --model-path /scratch/nlp/jiazixia/rl_enhanced/PartialLabelingCSL-zsc/outputs/neg/rps7_time1/model-14-1283.ckpt
python3 test.py --model-path /scratch/nlp/jiazixia/rl_enhanced/PartialLabelingCSL-zsc/outputs/neg/rps7_time1/model-15-1283.ckpt
python3 test.py --model-path /scratch/nlp/jiazixia/rl_enhanced/PartialLabelingCSL-zsc/outputs/neg/rps7_time1/model-16-1283.ckpt
python3 test.py --model-path /scratch/nlp/jiazixia/rl_enhanced/PartialLabelingCSL-zsc/outputs/neg/rps7_time1/model-17-1283.ckpt
python3 test.py --model-path /scratch/nlp/jiazixia/rl_enhanced/PartialLabelingCSL-zsc/outputs/neg/rps7_time1/model-18-1283.ckpt
python3 test.py --model-path /scratch/nlp/jiazixia/rl_enhanced/PartialLabelingCSL-zsc/outputs/neg/rps7_time1/model-19-1283.ckpt
python3 test.py --model-path /scratch/nlp/jiazixia/rl_enhanced/PartialLabelingCSL-zsc/outputs/neg/rps7_time1/model-20-1283.ckpt
python3 test.py --model-path /scratch/nlp/jiazixia/rl_enhanced/PartialLabelingCSL-zsc/outputs/neg/rps7_time1/model-21-1283.ckpt
python3 test.py --model-path /scratch/nlp/jiazixia/rl_enhanced/PartialLabelingCSL-zsc/outputs/neg/rps7_time1/model-22-1283.ckpt
python3 test.py --model-path /scratch/nlp/jiazixia/rl_enhanced/PartialLabelingCSL-zsc/outputs/neg/rps7_time1/model-23-1283.ckpt
python3 test.py --model-path /scratch/nlp/jiazixia/rl_enhanced/PartialLabelingCSL-zsc/outputs/neg/rps7_time1/model-24-1283.ckpt
python3 test.py --model-path /scratch/nlp/jiazixia/rl_enhanced/PartialLabelingCSL-zsc/outputs/neg/rps7_time1/model-25-1283.ckpt
